//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bowerbird.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bowerbird.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;bbfont name=&quot;Bowerbird&quot; style=&quot;bold&quot; version=&quot;1.0&quot;&gt;
        ///  &lt;!-- SPACE --&gt;
        ///  &lt;letter code=&quot;32&quot; start=&quot;0.2&quot; end=&quot;0.5&quot; /&gt;
        ///  &lt;!-- NULL --&gt;
        ///  &lt;letter code=&quot;0&quot; start=&quot;0&quot; end=&quot;0.7&quot;&gt;
        ///    &lt;path x=&quot;0.10&quot; y=&quot;0.90&quot;&gt;
        ///      &lt;to x=&quot;0.60&quot; y=&quot;0.90&quot; /&gt;
        ///      &lt;to x=&quot;0.60&quot; y=&quot;0.10&quot; /&gt;
        ///      &lt;to x=&quot;0.10&quot; y=&quot;0.10&quot; /&gt;
        ///      &lt;to x=&quot;0.10&quot; y=&quot;0.90&quot; /&gt;
        ///    &lt;/path&gt;
        ///    &lt;path x=&quot;0.05&quot; y=&quot;1.00&quot;&gt;
        ///      &lt;to x=&quot;0.65&quot; y=&quot;1.00&quot; /&gt;
        ///      &lt;to x=&quot;0.70&quot; y=&quot;0.95&quot; b=&quot;0.414213562373095&quot; /&gt;
        ///      &lt;to [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string bowerbird_bold {
            get {
                return ResourceManager.GetString("bowerbird_bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;bbfont name=&quot;Bowerbird&quot; style=&quot;regular&quot; version=&quot;1.0&quot;&gt;
        ///  &lt;!-- SPACE --&gt;
        ///  &lt;letter code=&quot;32&quot; start=&quot;0.20&quot; end=&quot;0.50&quot; /&gt;
        ///  &lt;!-- NULL --&gt;
        ///  &lt;letter code=&quot;0&quot; start=&quot;0&quot; end=&quot;0.7&quot;&gt;
        ///    &lt;path x=&quot;0.05&quot; y=&quot;0.95&quot;&gt;
        ///      &lt;to x=&quot;0.65&quot; y=&quot;0.95&quot; /&gt;
        ///      &lt;to x=&quot;0.65&quot; y=&quot;0.05&quot; /&gt;
        ///      &lt;to x=&quot;0.05&quot; y=&quot;0.05&quot; /&gt;
        ///      &lt;to x=&quot;0.05&quot; y=&quot;0.95&quot; /&gt;
        ///    &lt;/path&gt;
        ///  &lt;/letter&gt;
        ///  &lt;!-- LATIN CAPITAL LETTER A --&gt;
        ///  &lt;letter code=&quot;65&quot; start=&quot;0.00&quot; end=&quot;0.70&quot;&gt;
        ///    &lt;path x=&quot;0.13333333333 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string bowerbird_regular {
            get {
                return ResourceManager.GetString("bowerbird_regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_asymptotic_path {
            get {
                object obj = ResourceManager.GetObject("icon_asymptotic_path", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_boolean {
            get {
                object obj = ResourceManager.GetObject("icon_boolean", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_curve_on_surface_construct {
            get {
                object obj = ResourceManager.GetObject("icon_curve_on_surface_construct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_curve_on_surface_curvature {
            get {
                object obj = ResourceManager.GetObject("icon_curve_on_surface_curvature", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_curve_on_surface_deconstruct {
            get {
                object obj = ResourceManager.GetObject("icon_curve_on_surface_deconstruct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_curve_on_surface_evaluate {
            get {
                object obj = ResourceManager.GetObject("icon_curve_on_surface_evaluate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_curve_on_surface_extrude {
            get {
                object obj = ResourceManager.GetObject("icon_curve_on_surface_extrude", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_curve_on_surface_geodesic_curvature {
            get {
                object obj = ResourceManager.GetObject("icon_curve_on_surface_geodesic_curvature", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_curve_on_surface_geodesic_torsion {
            get {
                object obj = ResourceManager.GetObject("icon_curve_on_surface_geodesic_torsion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_curve_on_surface_normal_curvature {
            get {
                object obj = ResourceManager.GetObject("icon_curve_on_surface_normal_curvature", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_difference {
            get {
                object obj = ResourceManager.GetObject("icon_difference", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_intersection {
            get {
                object obj = ResourceManager.GetObject("icon_intersection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_layer {
            get {
                object obj = ResourceManager.GetObject("icon_layer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_normalize {
            get {
                object obj = ResourceManager.GetObject("icon_normalize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_offset {
            get {
                object obj = ResourceManager.GetObject("icon_offset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_pathfinder {
            get {
                object obj = ResourceManager.GetObject("icon_pathfinder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_principal_path {
            get {
                object obj = ResourceManager.GetObject("icon_principal_path", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_radial {
            get {
                object obj = ResourceManager.GetObject("icon_radial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_section {
            get {
                object obj = ResourceManager.GetObject("icon_section", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_text {
            get {
                object obj = ResourceManager.GetObject("icon_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_union {
            get {
                object obj = ResourceManager.GetObject("icon_union", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_waffle {
            get {
                object obj = ResourceManager.GetObject("icon_waffle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_xor {
            get {
                object obj = ResourceManager.GetObject("icon_xor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_24 {
            get {
                object obj = ResourceManager.GetObject("logo_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
